import 'package:warchest_dojo/const/unit_class_const.dart';

class UnitSpec {
  static const List<Map<String, dynamic>> unitSpec = [
    {
      "unit_class": UnitClassConst.sword,
      "symbol": "剣",
      "quantity": 5,
      "name": "剣兵",
      "color": 0xFF36507C,
    },
    {
      "unit_class": UnitClassConst.crossbow,
      "symbol": "弩",
      "quantity": 5,
      "name": "弩兵",
      "color": 0xFF9B5B63,
    },
    {
      "unit_class": UnitClassConst.knight,
      "symbol": "重",
      "quantity": 4,
      "name": "重装兵",
      "color": 0xFF009ED1,
    },
    {
      "unit_class": UnitClassConst.archer,
      "symbol": "弓",
      "quantity": 4,
      "name": "弓兵",
      "color": 0xFF68B199,
    },
    {
      "unit_class": UnitClassConst.cavalry,
      "symbol": "騎",
      "quantity": 4,
      "name": "騎兵",
      "color": 0xFFD48242,
    },
    {
      "unit_class": UnitClassConst.lightCavalry,
      "symbol": "軽",
      "quantity": 5,
      "name": "軽騎兵",
      "color": 0xFF9CB96B,
    },
    {
      "unit_class": UnitClassConst.lancer,
      "symbol": "突",
      "quantity": 4,
      "name": "突撃騎兵",
      "color": 0xFFDF4B3E,
    },
    {
      "unit_class": UnitClassConst.pike,
      "symbol": "槍",
      "quantity": 4,
      "name": "槍兵",
      "color": 0xFFD8B448,
    },
    {
      "unit_class": UnitClassConst.berserker,
      "symbol": "狂",
      "quantity": 5,
      "name": "狂戦士",
      "color": 0xFF3E895A,
    },
    {
      "unit_class": UnitClassConst.royalGuard,
      "symbol": "衛",
      "quantity": 5,
      "name": "衛兵",
      "color": 0xFFDD7C7B,
    },
    {
      "unit_class": UnitClassConst.ensign,
      "symbol": "旗",
      "quantity": 5,
      "name": "旗兵",
      "color": 0xFFBFC367,
    },
    {
      "unit_class": UnitClassConst.marshall,
      "symbol": "帥",
      "quantity": 5,
      "name": "総帥",
      "color": 0xFFC56647,
    },
    {
      "unit_class": UnitClassConst.footman,
      "symbol": "従",
      "quantity": 5,
      "name": "従兵",
      "color": 0xFF009199,
    },
    {
      "unit_class": UnitClassConst.warriorPriest,
      "symbol": "僧",
      "quantity": 4,
      "name": "僧兵",
      "color": 0xFF745665,
    },
    {
      "unit_class": UnitClassConst.mercenary,
      "symbol": "傭",
      "quantity": 5,
      "name": "傭兵",
      "color": 0xFF912C31,
    },
    {
      "unit_class": UnitClassConst.scout,
      "symbol": "偵",
      "quantity": 5,
      "name": "偵察兵",
      "color": 0xFF0470B0,
    },
    {
      "unit_class": UnitClassConst.blueRoyal,
      "symbol": "勅",
      "quantity": 1,
      "name": "勅令",
      "color": 0xFF3CBCD4,
    },
    {
      "unit_class": UnitClassConst.redRoyal,
      "symbol": "勅",
      "quantity": 1,
      "name": "勅令",
      "color": 0xFFE040FB,
    },
  ];
}
